name: CI/CD with Docker

on:
  push:
    branches:
      - main # Adjust the branch name as needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t app.py:1.0 .
          docker push app.py:1.0

      - name: Run Docker container
        run: |
          docker run -d -p 3000:3080 app.py:1.0
